####### Base Config #######
  baseURL = "https://img.youronly.one/"             # .Site.BaseURL
  title = "Blog Images"                                        # .Site.Title; IMPT for Schema.org; OpenGraph; Twitter Cards -- for RDFa, Microdata, JSON-LD
  copyright = ""                                            # .Site.Copyright; leave empty and uncommented to override theme default; we are using our own footer
  timeZone = "Etc/UTC"


####### Site settings #######
  paginate = 100
  #paginatePath = "page"                                     # https://example.com/page/2
  rssLimit = 20
  #summaryLength = 100                                       # default: 70

  #### Other settings ####
    #disqusShortname = "youronlyone"                         # .Site.DisqusShortname
    #googleAnalytics = ""                                    # .Site.GoogleAnalytics


####### Backend settings #######
  canonifyURLs = true                                       # true for our use-case
  #disableAliases = true                                     # use this if we want to use server redirects
  enableEmoji = false                                       # format :smile:.
  enableGitInfo = false
  relativeURLs = false                                      # false for our use-case; make all relative URLs relative to content root
  refLinksNotFoundURL = "https://img.youronly.one/"

  ## Dev settings ##
    publishDir = "public"
    enableMissingTranslationPlaceholders = true
    timeout = "30s"

  ## Other settings ##
    #PygmentsCodeFences = true
    #PygmentsStyle = "monokai"
    disableKinds = ["robotsTXT", "section", "taxonomy", "term"]

#### LANG stuff ####
  defaultContentLanguage = "en"
  defaultContentLanguageInSubdir = false
  hasCJKLanguage = true
  languageCode = "en"

  ## Theme settings ##
  ## Theme settings ##


#######  #######  #######  #######  #######  #######  #######  #######


[mediaTypes]
  [mediaTypes."image/avif"]
    suffixes = ["avif"]

  ## .awebp is only a personal extension since animated .webp is causing errors
  ## a temporary workaround
  [mediaTypes."image/webp"]
    suffixes = ["webp", "awebp"]

  ## .apng should be redeclared as image/png to get Resize working
  ## The resized version won't animate.
  [mediaTypes."image/png"]
    suffixes = ["png", "apng"]


#######  #######  #######  #######  #######  #######  #######  #######


[caches]
    [caches.images]
        dir    = ':cacheDir/gallerydeluxe'
        maxAge = "80h"

[server]
    [[server.headers]]
        for = '/**'
        [server.headers.values]
            Referrer-Policy = 'strict-origin-when-cross-origin'

[params]
    [params.gallerydeluxe]
