# See: https://gohugo.io/getting-started/configuration/

####### BASE CONFIG #######
  baseURL = "https://images.youronly.one/"                                              # .Site.BaseURL
  title = "YourOnly.One: Blog Images"                                                # .Site.Title; IMPT for Schema.org; OpenGraph; Twitter Cards; RDFa, Microdata, JSON-LD
  copyright = ""                                            # .Site.Copyright; leave empty to override theme
  timeZone = "Etc/UTC"


####### FRONTEND #######
  paginate = 100                                             # default: 10
  rssLimit = 25                                             # default: -1
  summaryLength = 240                                        # default: 70
  titleCaseStyle = "firstupper"                                     # default: AP; our choice: firstupper; backup: Chicago


####### LANGUAGE #######
  languageCode = "en"
  defaultContentLanguage = "en"                             # default: en
  hasCJKLanguage = true                                    # default: false
  # Our LANG: 'en', 'en-ph', 'fil', 'phi-hang', 'tl-tglg', 'zh-hant', 'zh-hans', 'zh-bopo', 'ja', 'ko'
  disableLanguages = ['en-ph', 'fil', 'phi-hang', 'tl-tglg', 'zh-hant', 'zh-hans', 'zh-bopo', 'ja', 'ko']


####### BACKEND #######

  disableKinds = ["robotsTXT", "section", "taxonomy", "term"]
  enableMissingTranslationPlaceholders = true              # default: false
  timeout = "170s"                                           # default: 30s


#######  #######  #######  #######  #######  #######  #######  #######


[mediaTypes]
  [mediaTypes."image/jpeg"]
    suffixes = ["jpeg", "jpg", "jpe", "jif", "jfif", "jfi"]
  [mediaTypes."image/gif"]
    suffixes = ["gif"]
  [mediaTypes."image/svg+xml"]
    suffixes = ["svgz", "svg"]

  # .apng should be redeclared as image/png to get Resize working
  # The resized version won't animate.
  [mediaTypes."image/png"]
    suffixes = ["apng", "png"]

  # .awebp is only a personal extension since animated .webp is causing errors
  # a temporary workaround
  [mediaTypes."image/webp"]
    suffixes = ["webp", "awebp"]

  [mediaTypes."image/avif"]
    suffixes = ["avif", "heif", "heifs", "hif"]


#######  #######  #######  #######  #######  #######  #######  #######


[outputFormats]
  [outputFormats.jfi]
    mediaType = "image/jpeg"
  [outputFormats.jfif]
    mediaType = "image/jpeg"
  [outputFormats.jif]
    mediaType = "image/jpeg"
  [outputFormats.jpe]
    mediaType = "image/jpeg"
  [outputFormats.jpg]
    mediaType = "image/jpeg"
  [outputFormats.jpeg]
    mediaType = "image/jpeg"
  [outputFormats.gif]
    mediaType = "image/gif"
  [outputFormats.svg]
    mediaType = "image/svg+xml"
  [outputFormats.svgz]
    mediaType = "image/svg+xml"

  # .awebp is only a personal extension since animated .webp is causing errors
  # a temporary workaround
  [outputFormats.png]
    mediaType = "image/png"
  [outputFormats.apng]
    mediaType = "image/png"

  [outputFormats.awebp]
    mediaType = "image/webp"
  [outputFormats.webp]
    mediaType = "image/webp"
  [outputFormats.hif]
    mediaType = "image/avif"
  [outputFormats.heifs]
    mediaType = "image/avif"
  [outputFormats.heif]
    mediaType = "image/avif"
  [outputFormats.avif]
    mediaType = "image/avif"


#######  #######  #######  #######  #######  #######  #######  #######
