# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

#favicon_mstilecolor = ""

### BGN: Structured Data ###
  siteStartYear = 2022
  description = "All the images used in articles in YourOnly.One blogs."
  keywords = ["YourOnlyOne", "YourOnly.One", "Yahuhanan Yukiya Sese Cuneta", "Yuki", "YoHan", "Yo-Han",  "יהוחנן", "ᜌᜓᜃᜒ", "사요한", "謝雪矢（ゆきや）", "스노", "Seu-No", "SeuNo", "Snow", "Yohanan", "ᜌᜓᜑᜈᜈ᜔", "ᜌᜓᜑᜈᜈ᜕", "ᜌᜑᜓᜑᜈᜈ᜔", "ᜌᜑᜓᜑᜈᜈ᜕"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/YOOki_Chronicles.webp", "https://rsc.youronly.one/img/y/Yuki_flag-300h.webp", "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"]
### END: Structured Data ###

### BGN: Theme settings
  [gallerydeluxe]
    # Shuffle the images in the gallery to give the impression of a new gallery each page load.
    shuffle = true

    # Reverse the order of the images in the gallery.
    reverse = true

    # Enable Exif data in the gallery.
    # See https://gohugo.io/content-management/image-processing/#exif-data for how to filter tags.
    enable_exif = false

    # Optional watermark file for the large images.
    #[gallerydeluxe.watermark]
    #    image = "images/gopher-hero8.png" # relative to /assets
    #    posx  = "left"                    # one of "left", "center", "right"
    #    posy  = "bottom"                  # one of "top", "center", "bottom"
### END: Theme settings

### BGN: Hugo module settings ###
  ##### BGN: syndication #####
    ## Custom entries only work if placed in per-site params.toml ##
    [[sns]]
      url = 'blogspot.com'
      icon = 'blogspot.svg'
    [[sns]]
      url = 'bsky.app'
      icon = 'bluesky.svg'
    [[sns]]
      url = 'c.im'
      icon = 'mastodon.png'
    [[sns]]
      url = 'c.wtf'
      icon = 'rebased.svg'
    [[sns]]
      url = 'catodon.social'
      icon = 'catodon.png'
    [[sns]]
      url = 'diasp.org'
      icon = 'diaspora.svg'
    [[sns]]
      url = 'ebin.club'
      icon = 'fediverse.svg'
    [[sns]]
      url = 'facebook.com'
      icon = 'facebook.svg'
    [[sns]]
      url = 'fb.com'
      icon = 'facebook.svg'
    [[sns]]
      url = 'fedia.io'
      icon = 'mbin.svg'
    [[sns]]
      url = 'fedia.social'
      icon = 'iceshrimp.png'
    [[sns]]
      url = 'instagram.com'
      icon = 'instagram.svg'
    [[sns]]
      url = 'mastodon.online'
      icon = 'mastodon.png'
    [[sns]]
      url = 'mastodon.social'
      icon = 'mastodon.png'
    [[sns]]
      url = 'naver.com'
      icon = 'naver.png'
    [[sns]]
      url = 'p.lu'
      icon = 'peertube.svg'
    [[sns]]
      url = 'pixelfed.social'
      icon = 'pixelfed.svg'
    [[sns]]
      url = 'plurk.com'
      icon = 'plurk.svg'
    [[sns]]
      url = 'reddit.com'
      icon = 'reddit.svg'
    [[sns]]
      url = 'socialhome.network'
      icon = 'socialhome-black.svg'
    [[sns]]
      url = 'spoutible.com'
      icon = 'spoutible.png'
    [[sns]]
      url = 'threads.net'
      icon = 'threads.svg'
    [[sns]]
      url = 'tumblr.com'
      icon = 'tumblr.svg'
    [[sns]]
      url = 'twitter.com'
      icon = 'twitter.svg'
    [[sns]]
      url = 'wordpress.com'
      icon = 'wordpress.svg'
    [[sns]]
      url = 'write.as'
      icon = 'writefreely.png'
    [[sns]]
      url = 'x.com'
      icon = 'x.svg'
    [[sns]]
      url = 'youtube.com'
      icon = 'youtube.svg'
    [[sns]]
      url = 'is.youronly.one'
      icon = 'bluesky.svg'
    [[sns]]
      url = 't.youronly.one'
      icon = 'tumblr.svg'
  ##### END: syndication #####
### END: Hugo module settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2021-02-06"
    sameas = [
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://www.youtube.com/@YourOnlyOneOfcl",
      "https://www.facebook.com/YourOnly.ONE.ofcl"
    ]
### END: Other Settings ###
