#mainSections = ["blog", "posts"]                                             # Hugo default
#mainTypes = ["article", "sitepage", "review"]                                                # YourOnly.One

rssfull = true
jquerycdn = false
websubhubs = ["https://pubsubhubbub.appspot.com/", "https://youronlyone.superfeedr.com/", "https://pubsubhubbub.superfeedr.com/", "https://websubhub.com/hub"]

#googleadsense = "ca-pub-8360283248006398"

### BGN: Structured Data ###
  siteStartYear = 2022

  description = "All the images used in articles in YourOnly.One blogs."
  license = "https://im.youronly.one/p/legal-notice/"
  keywords = ["YourOnly.One", "Yuki", "ᜌᜓᜃᜒ"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/YOOki_Chronicles.webp", "https://rsc.youronly.one/img/y/Yuki_flag-300h.webp", "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"]
  #copyright = ""
### END: Structured Data ###

### BGN: Theme settings
  [gallerydeluxe]
    # Shuffle the images in the gallery to give the impression of a new gallery each page load.
    shuffle = true

    # Reverse the order of the images in the gallery.
    reverse = true

    # Enable Exif data in the gallery.
    # See https://gohugo.io/content-management/image-processing/#exif-data for how to filter tags.
    enable_exif = false
### END: Theme settings

### BGN: Other Settings ###
  [semweb]
    org = "yelosan"

    #isni = ""
    #issn = ""
    acquirelicensepage = "https://im.youronly.one/p/legal-notice/"
    copyrightnotice = "Copyleft 🄯 CC-BY-SA 4.0 International by JC John Sese Cuneta"
    credittext = "I'M YourOnly.One (https://im.youronly.one/)"
    datecreated = "2021-02-06"
    isblog = true
    license = "https://im.youronly.one/p/legal-notice/"
    publisher = "https://yelosan.youronly.one/"
    sameas = [
      "https://facebook.com/101597304949708/",
      "https://facebook.com/yelosanpub/",
      "https://c.im/@youronlyone",
      "https://mastodon.social/@youronlyone",
      "https://mastodon.online/@youronlyone",
      "https://pixelfed.social/youronlyone",
      "https://youtube.com/YourOnlyONEofcl",
      "https://twitter.com/YourOnlyONEofcl",
      "https://instagram.com/YourOnly.One",
      "https://facebook.com/YourOnly.ONE.ofcl",
      "https://www.pinterest.com/YourOnlyONEofcl",
      "https://www.eyeem.com/u/YourOnlyOne",
      "https://www.goodreads.com/youronlyone",
      "https://vero.co/youronlyone",
      "https://ecency.com/@youronlyone",
      "https://hive.blog/@youronlyone",
      "https://steemit.com/@youronlyone",
      "https://gitlab.com/techmagus",
      "https://github.com/techmagus"
    ]

    [[semweb.persons]]
      person = "yuki"
      #id = ""
      #name = ""ᜌᜓᜃᜒ (雪亮 | 스노 | Yuki)"
      #url = ""
      #avatar = ""
      #rel = "noopener external nofollow"

  [verify]
    flattr = "4j1gl5"
    wot = "06c7ef6e7986586661ef"
    ocs = "c563648adcfa021a0dfd3d3d8f0be64a"
    followit = "jqEnpsdBvHltNryJFB4A"

  [analytics]
    cfwebanalytics = "07a05e5302d1458da3561ce41791e284"
    microanalyticsio = "ZwSg9rf6GA"
    naver = "1375cb4224f1c40"   # https://youronly.one
    #naver = "137a7c92882ac90"   # https://im.youronly.one
    counterdev = "youronlyone"
    swetrix = "bYdcXUajNvru"
    microsoftclarity = "63ddi0b99e"
### END: Other Settings ###
