# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

#favicon_mstilecolor = ""

### BGN: Structured Data ###
  siteStartYear = 2022
  description = "All the images used in articles in YourOnly.One blogs."
  keywords = ["YourOnly.One", "Yuki", "ᜌᜓᜃᜒ"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/YOOki_Chronicles.webp", "https://rsc.youronly.one/img/y/Yuki_flag-300h.webp", "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"]
### END: Structured Data ###

### BGN: Theme settings
  [gallerydeluxe]
    # Shuffle the images in the gallery to give the impression of a new gallery each page load.
    shuffle = true

    # Reverse the order of the images in the gallery.
    reverse = true

    # Enable Exif data in the gallery.
    # See https://gohugo.io/content-management/image-processing/#exif-data for how to filter tags.
    enable_exif = false

    # Optional watermark file for the large images.
    #[gallerydeluxe.watermark]
    #    image = "images/gopher-hero8.png" # relative to /assets
    #    posx  = "left"                    # one of "left", "center", "right"
    #    posy  = "bottom"                  # one of "top", "center", "bottom"
### END: Theme settings

### BGN: Other Settings ###
  [semweb]
    datecreated = "2021-02-06"
    sameas = [
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://hashi.icu/@YourOnlyOne",
      "https://www.youtube.com/@YourOnlyOneOfcl",
      "https://www.facebook.com/YourOnly.ONE.ofcl"
    ]
### END: Other Settings ###
